<link rel="stylesheet" type="text/css" media="all" href="/css/jquery-ui-1.8.16.custom.css" />
<script type="text/javascript" src="/js/jquery-ui-1.8.16.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.maskMoney.js"></script>

<h3 align="center">Pesquisa Detalhada do Imóvel</h3>

<?php if (is_array($this->message)) :?>
<?php foreach ($this->message as $msg) :?>
<h3><?php echo $msg; ?></h3>
<?php endforeach;?>
<?php endif;?>

<div align="center">
	<form id="pesquisa_imovel" method="post" action="" enctype="application/x-www-form-urlencoded" name="pesquisa_imovel">
		<fieldset>
			<legend>Detalhes da pesquisa</legend>
			<div id="accordion">
				<h3>
					<a href="#">Dados Basicos</a>
				</h3>
				<div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
							<?php echo $this->form->status_imovel; ?>
						</div>
						<div class='campo_longo'>
							<?php echo $this->form->valor_imovel; ?>
						</div>
					</div>
					<div style='clear: both;'>&nbsp;</div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
							<?php echo $this->form->tipo_imovel; ?>
						</div>
						<div class='campo_longo'>
							<?php echo $this->form->categoria_imovel; ?>
						</div>
					</div>
					<div style='clear: both;'>&nbsp;</div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
						<?php echo $this->form->imovel; ?>
						</div>
						<div class='campo_longo'>
						<?php echo $this->form->promotor; ?>
						</div>
					</div>
					<div style='clear: both;'>&nbsp;</div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
						<?php echo $this->form->area_construida; ?>
						</div>
						<div class='campo_longo'>
						<?php echo $this->form->local_chave; ?>
						</div>
					</div>
				</div>

				<h3>
					<a href="#">Detalhes do Imóvel</a>
				</h3>
				<div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
						<?php echo $this->form->dormitorios; ?>
						</div>
						<div class='campo_longo'>
						<?php echo $this->form->suite; ?>
						</div>
					</div>
					<div style='clear: both;'>&nbsp;</div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
						<?php echo $this->form->vagas_carro; ?>
						</div>
						<div class='campo_longo'>
						<?php echo $this->form->area_lazer; ?>
						</div>
					</div>
					<div style='clear: both;'>&nbsp;</div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
						<?php echo $this->form->valor_iptu; ?>
						</div>
						<div class='campo_longo'>
						<?php echo $this->form->valor_condominio; ?>
						</div>
					</div>
					<div style='clear: both;'>&nbsp;</div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
						<?php echo $this->form->total_comodos; ?>
						</div>
						<div class='campo_longo'>
						<?php echo $this->form->area_servico; ?>
						</div>
					</div>
					<div style='clear: both;'>&nbsp;</div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
						<?php echo $this->form->metragem_terreno; ?>
						</div>
						<div class='campo_longo'>
						<?php echo $this->form->ano_construcao; ?>
						</div>
					</div>
				</div>

				<h3>
					<a href="#">Localização</a>
				</h3>
				<div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
						<?php echo $this->form->tipo_endereco; ?>
						</div>
						<div class='campo_longo'>
						<?php echo $this->form->zona; ?>
						</div>
					</div>

					<div style='clear: both;'>&nbsp;</div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
						<?php echo $this->form->logradouro; ?>
						</div>
						<div class='campo_longo'>
						<?php echo $this->form->numero_end; ?>
						</div>
					</div>
					<div style='clear: both;'>&nbsp;</div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
						<?php echo $this->form->bairro; ?>
						</div>
						<div class='campo_longo'>
						<?php echo $this->form->cep; ?>
						</div>
					</div>
					<div style='clear: both;'>&nbsp;</div>
					<div class='campo_tupla'>
						<div class='campo_longo'>
						<?php echo $this->form->cidade; ?>
						</div>
						<div class='campo_longo'>
						<?php echo $this->form->estado; ?>
						</div>
					</div>
				</div>
			</div>

			<div style="text-align: center;">
			<?php echo $this->form->autenticar; ?>
			</div>

		</fieldset>
	</form>
</div>

<!-- 
<a href="" target="_blank" onclick="Nova.janela('/imobiliaria/clientes/cadastrar'); return false;">LINK TESTE NOVA JANELA POPUP</a>
 -->
	
<script type="text/javascript">
	Cnpj.mascara();
	Telefone.mascara();
	Data.mascara();
	
	Accordion.mascara();
	Cpf.mascara();
	Cep.mascara();

	Moeda.validar();
	//Digitos.dois();
	//Digitos.quatro();

	//Digitos.seis();
</script>
